#!/usr/bin/env bash
# vim: noai:ts=4:sw=4:expandtab
# script: bspwmporn 
# describe: Linux Mint, Ubuntu and Debian install bspwm + polybar and more
# author: Wedsley Fernando Da Silva Milouchine  - <https://github.com/WedsleyFernando>
# version: 1.1
# license: GNU GPLv3

version="${0##*/} version 1.2"

[[ $(echo $LANG | cut -c 1-2) == "pt" ]] && _MSG="Não use 'sudo' e nem 'root'" || _MSG="Do not use 'sudo' or 'root'"
[[ $(id -u) -eq 0 ]] && echo ${_MSG} && exit 1

CURRENT_DIR=$(pwd)

shopt -s extglob


_start(){
cat <<EOF
 _                                                        
| |__  ___ _ ____      ___ __ ___  _ __   ___  _ __ _ __  
| '_ \/ __| '_ \ \ /\ / / '_ ' _ \| '_ \ / _ \| '__| '_  \ 
| |_) \__ \ |_) \ V  V /| | | | | | |_) | (_) | |  | | | |
|_.__/|___/ .__/ \_/\_/ |_| |_| |_| .__/ \___/|_|  |_| |_|
          |_|                     |_|                     

EOF
}

usage() {
_start
cat <<EOF
usage: ${0##*/} [flags]
  Options:
    --install,   -i  Install bspwmporn  (ODB)
    --unistall,  -u  Uninstall bspwmporn
    --dotfiles,  -d  Install only dotfiles 
    --show-deps, -s  Show all dependencys 
    --version,   -v  Show version
    --help,      -h  Show this is message
    --update,    -U  Update your system (ODB)

* ODB  Only debian-based
* Wedsley Fernando Da Silva Milouchine  - <https://github.com/WedsleyFernando> - BSPWMPORN 1.2
EOF
}


if [[ -z $1 || $1 = @(-h|--help) ]]; then
    usage
    exit $(( $# ? 0 : 1 ))
fi


_show_dependency() {
_start
cat <<EOF
    List of Dependencys

        BROWSER 
            Opera                                 { https://www.opera.com/pt-br }
            Extension of Chrome for Opera 
            Vimium (Extension for Opera)          { Extension for Google Chrome}
            
        WINDOW MANAGER
            bspwm  (Manage window)                { https://github.com/baskerville/bspwm }
            sxhkd (shortcuts)                     { https://github.com/baskerville/sxhkd }
            feh (For set Background)              
            picom (For animations)                { https://github.com/jonaburg/picom }

        TERMINAL
            fonts (powerline fonts)               { https://github.com/romkatv/powerlevel10k }
            fzf
            neovim(With SpaceVim)                 { https://github.com/WedsleyFernando/Spacevim }
            ranger 
            gnome-terminal
            git
            compton
            numlockx
            imagemagick (Depedency of Feh) 
            webp
            lxappearance
            neofetch
            cava

        NOTIFICATION
            dunst                                 { https://github.com/dunst-project/dunst}

        MENU
            rofi                                  { https://github.com/davatorium/rofi }

        TOUCHPAD
            Gestures                              { https://github.com/bulletmark/libinput-gestures }
EOF
}

_updates(){
    sudo apt update
    sudo apt full-upgrade -y
    sudo apt clean
    sudo apt autoremove -y
    sudo apt autoclean
    exit 0
}

_deps_build(){
    sudo apt install -y build-essential \
    cmake cmake-data pkg-config libcairo2-dev \
    libxcb1-dev libxcb-util0-dev libxcb-randr0-dev \
    libxcb-composite0-dev python3-xcbgen xcb-proto \
    libxcb-image0-dev libxcb-ewmh-dev \
    libxcb-icccm4-dev \ libcurl4-openssl-dev libjsoncpp-dev libpulse-dev\
    libmpdclient-dev libasound2-dev libxcb-cursor-dev\
    libxcb-xrm-dev libxcb-xkb-dev libnl-genl-3-dev libcurl4-openssl-dev
}

_apt_packs(){
    sudo apt install -y bspwm sxhkd\
    subversion rofi feh numlockx\
    compton dunst neofetch imagemagick\
    ranger neovim lxappearance fzf\
    webp unifont gnome-terminal git\
    python3 python3-pip

    #pip install
    sudo pip3 install sphinx

    # Install Cava
    sudo add-apt-repository ppa:hsheth2/ppa && sudo apt-get update && sudo apt-get install cava
}

_build_polybar(){
    cd /tmp
    git clone --recursive https://github.com/polybar/polybar
    cd polybar/
    sed -i 's/read /#read /g' build.sh
    sudo ./build.sh -A -a -p -n -m -c -g 
}


_git_svn_packs(){
    [[ ! -d "${HOME}/.local/share/fonts" ]] && mkdir -p "${HOME}/.local/share/fonts"
    svn export https://github.com/terroo/fonts/trunk/fonts
    mv fonts ${HOME}/.local/share/fonts/
    fc-cache -fv
}

_install_theme_terminal(){
    git clone https://github.com/lemnos/theme.sh.git
    sudo mv theme.sh/theme.sh /usr/bin/terminal-theme
}

_cfg_all(){
    cd $CURRENT_DIR
    mv bspwm/ ${HOME}/.config/ 
    mv sxhkd/ ${HOME}/.config/ 
    mv dunst/ ${HOME}/.config/ 
    mv polybar/ ${HOME}/.config/ 
    mv rofi/ ${HOME}/.config/
    mv picom/ ${HOME}/.config/
    mv wallpapers/groot.jpg ${HOME}/.wallpaper.jpg
    feh --bg-scale ${HOME}/.wallpaper.jpg
    NETW=$(ip addr | awk '/state UP/ {print $2}' | sed 's/://g')
    sed -i -r "s/[a-z0-9]+ ;redoo/$NETW/g" ${HOME}/.config/polybar/modules.ini
    [[ $(grep -i 'mint' /etc/issue) ]] && _d=" Linux Mint"
    [[ $(grep -i 'ubuntu' /etc/issue) ]] && _d=" Ubuntu"
    [[ $(grep -i 'debian' /etc/issue) ]] && _d=" Debian"
    sed -i "s/DISTROOO/$_d/" ${HOME}/.config/polybar/user_modules.ini
}

_cfg_all_dotfiles(){
    cd $CURRENT_DIR
    mv bspwm/ ${HOME}/.config/ 
    mv sxhkd/ ${HOME}/.config/ 
    mv dunst/ ${HOME}/.config/ 
    mv polybar/ ${HOME}/.config/ 
    mv rofi/ ${HOME}/.config/
    mv picom/ ${HOME}/.config/
    mv wallpapers/groot.jpg ${HOME}/.wallpaper.jpg
}


_ok(){
    clear
    echo "INSTALLATION FINISHED!"
    _start
}

_install(){
    _start
    _apt_packs
    _deps_build
    _install_theme_terminal
    [[ ! $(which cmake 2>/dev/null) ]] && _deps_build
    _git_svn_packs
    [[ $(grep -i 'debian' /etc/issue) ]] && sudo apt -y install polybar || _build_polybar
    _cfg_all
    _ok
    exit 0
}

_install_dotfiles(){
    _start
    _install_theme_terminal
    _cfg_all
    _ok
    exit 0
}

_uninstall(){
    sudo apt remove -y bspwm rofi
    sudo rm $(which polybar)
    rm -rf ${HOME}/.fehbg ${HOME}/.wallpaper.jpg
    rm -rf ${HOME}/.local/share/fonts/fonts
    rm -rf ${HOME}/.config/{bspwm,sxhkd,polybar,rofi,dunst,picom}
    exit 0
}

while [[ "$1" ]]; do
    case "$1" in
        "--install"|"-i") _install ;;
        "--uninstall"|"-u") _uninstall ;;
        "--dotfiles"|"-d") _install_dotfiles ;;
        "--show-deps"|"-s") _show_dependency ;;
        "--help"|"-h") usage ;;
        "--version"|"-v") printf "%s\n" "$version" && exit 0 ;;
        "--update"|"-U") _updates && exit 0 ;;
        *) echo 'Invalid option.' && usage && exit 1 ;;
    esac
    shift
done
