#! /bin/sh

sxhkd &

# Configure two monitors if you have
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; 
then
    bspc monitor HDMI-1 -d I II III IV V 
    bspc monitor eDP-1  -d VI VII VIII IX X
    bspc monitor eDP-1  -s HDMI-1
    xrandr --output HDMI-1 --primary --mode 2560x1080 --rate 75.00 --left-of eDP-1
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi



bspc config border_width         6
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color \#2E3436  # janela não ativa
bspc config active_border_color \#CCCCCC # ?
bspc config focused_border_color \#121617 # janela ativa
bspc config presel_feedback_color \#FFFFFF # ?

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Yad desktop='^1' state=floating follow=on
#bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mytask state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
$HOME/.fehbg
/usr/bin/numlockx on
#/usr/libexec/gsd-xsettings &
setxkbmap -model abnt2 -layout br -variant abnt2
dunst &
compton &
#mytask &
