#! /bin/sh
#Configs side of monitors BSPWM
SECOND_MONITOR_SIDE="left"
THIRD_MONITOR_SIDE="rigth"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')
THIRD_MONITOR=$(xrandr | grep connected | awk '{i++}i==3'| awk '{print $1}')

sxhkd &

# Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  bspc monitor $(bspc query -M | sed -n 3p) -d XI XII XIII XIV XV 
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
  xrandr --output $THIRD_MONITOR --$THIRD_MONITOR_SIDE-of $PRINCIPAL  
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV V
  bspc monitor $(bspc query -M | sed -n 2p) -d VI VII VIII IX X
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
else
  bspc monitor -d I II III IV V VI VII VIII IX X 
fi


bspc config border_width         6
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color \#121617 # janela não ativa
bspc config active_border_color \#FFFFFF # ?
bspc config focused_border_color \#2E3436  # janela ativa
bspc config presel_feedback_color \#CCCCCC  # ?

#Rules set Ex: Floating window
bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Yad desktop='^1' state=floating follow=on
#bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mytask state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# call init script polybar
$HOME/.config/polybar/launch.sh --shapes &
# call background setter
$HOME/.fehbg
#set on numlock
/usr/bin/numlockx on
#set to abnt2 BR layout keyboard
setxkbmap -model abnt2 -layout br -variant abnt2
#init dunst notification 
dunst &
compton &
#mytask &
