#!/bin/bash

if [ "$(playerctl status >>/dev/null 2>&1; echo $?)" == "1" ]
then
	echo "None Music Playing at time"
	exit 0
fi

if [ "$(playerctl status)" == "Playing" ]
then
	title=$(playerctl metadata xesam:title)
	artist=$(playerctl metadata xesam:artist)
	echo "Youtube: $title | $artist"
else
	echo "Youtube: Music Stopped"
fi
